set(CVH_IMGPROC_TEST_SOURCES
    test/imgproc/arithmetic/accumulate_test.cpp
    test/imgproc/arithmetic/blend_linear_test.cpp
    test/imgproc/color/colormap_test.cpp
    test/imgproc/color/cvtcolor_rgb_gray_test.cpp
    test/imgproc/color/cvtcolor_two_plane_test.cpp
    test/imgproc/color/cvtcolor_yuv420_test.cpp
    test/imgproc/color/cvtcolor_yuv422_test.cpp
    test/imgproc/color/cvtcolor_yuv444_test.cpp
    test/imgproc/color/demosaicing_test.cpp
    test/imgproc/feature/canny_test.cpp
    test/imgproc/filtering/bilateral_filter_test.cpp
    test/imgproc/filtering/box_filter_test.cpp
    test/imgproc/filtering/copy_make_border_test.cpp
    test/imgproc/filtering/derivatives_test.cpp
    test/imgproc/filtering/filter2d_test.cpp
    test/imgproc/filtering/gaussian_blur_test.cpp
    test/imgproc/filtering/kernels_test.cpp
    test/imgproc/filtering/median_blur_test.cpp
    test/imgproc/filtering/sep_filter2d_test.cpp
    test/imgproc/filtering/sqr_box_filter_test.cpp
    test/imgproc/filtering/stack_blur_test.cpp
    test/imgproc/geometry/convert_maps_test.cpp
    test/imgproc/geometry/pyramid_test.cpp
    test/imgproc/geometry/rect_sub_pix_test.cpp
    test/imgproc/geometry/remap_test.cpp
    test/imgproc/geometry/resize_test.cpp
    test/imgproc/geometry/transform_matrix_test.cpp
    test/imgproc/geometry/warp_affine_test.cpp
    test/imgproc/geometry/warp_perspective_test.cpp
    test/imgproc/integration/basic_pipeline_test.cpp
    test/imgproc/intensity/adaptive_threshold_test.cpp
    test/imgproc/intensity/equalize_hist_test.cpp
    test/imgproc/intensity/lut_test.cpp
    test/imgproc/intensity/threshold_test.cpp
    test/imgproc/internal/derivatives_dispatch_test.cpp
    test/imgproc/internal/median_blur_dispatch_test.cpp
    test/imgproc/internal/pyramid_dispatch_test.cpp
    test/imgproc/morphology/morphology_test.cpp
    test/imgproc/statistics/integral_test.cpp
    test/imgproc/upstream/canny_upstream_test.cpp
    test/imgproc/upstream/copy_make_border_upstream_test.cpp
    test/imgproc/upstream/filter_upstream_test.cpp
    test/imgproc/upstream/morphology_derivatives_upstream_test.cpp
    test/imgproc/upstream/resize_upstream_test.cpp
)
