// AUTO-GENERATED by scripts/sync_opencv_core_channel_cases.py
// Upstream OpenCV commit: d719c6d
// Source: modules/core/test/test_operations.cpp
// This file intentionally stores exact upstream TEST blocks.
// Do not edit manually; re-run sync script.

// BEGIN Core_Array.expressions
TEST(Core_Array, expressions) { CV_OperationsTest test; test.safe_run(); }
// END Core_Array.expressions

